name: My CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./deploy-staging.sh

lint:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Super-Linter
      uses: super-linter/super-linter@v5.4.0
        env:
          GITHUB_TOKEN: ${{secrets.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}}
